version: '3'
services:
  radarr:
    restart: unless-stopped
    ports: 
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    volumes:
      - type: volume
        source: nfs-media
        target: /srv/media
        volume: 
          nocopy: true
    privileged: true
    build: radarr/

  sonarr:
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    volumes:
      - type: volume
        source: nfs-media
        target: /srv/media
        volume: 
          nocopy: true
    privileged: true
    build: sonarr/
  
  jellyfin:
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    image: linuxserver/jellyfin
 
volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.114,nolock,soft,rw,no_subtree_check"
      device: ":/srv/smbdata/media"
