version: '3'
services:
  radarr:
    restart: unless-stopped
    ports: 
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    volumes:
      - type: volume
        source: nfs-media
        target: /srv/media
        volume: 
          nocopy: true
    volumes:
      - type: volume
        source: nfs-radarr-cfg
        target: /config
        volume:
          nocopy: true
    privileged: true
    image: linuxserver/radarr

  sonarr:
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    volumes:
      - type: volume
        source: nfs-media
        target: /srv/media
        volume: 
          nocopy: true
    volumes:
      - type: volume
        source: nfs-sonarr-cfg
        target: /config
        volume:
          nocopy: true
    privileged: true
    image: linuxserver/sonarr
  
  jellyfin:
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    volumes:
      - type: volume
        source: nfs-media
        target: /srv/media
        volume: 
          nocopy: true
    image: linuxserver/jellyfin


  prowlarr:
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Berlin
    volumes:
      - type: volume
        source: nfs-prowlarr-cfg
        target: /config
        volume:
          nocopy: true
    image: linuxserver/prowlarr:develop
 
volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.114,nolock,soft,rw"
      device: ":/srv/smbdata/media"
  nfs-radarr-cfg:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.114,nolock,soft,rw"
      device: ":/srv/smbdata/media/config/radarr"
  nfs-sonarr-cfg:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.114,nolock,soft,rw"
      device: ":/srv/smbdata/media/config/sonarr"
  nfs-prowlarr-cfg:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.114,nolock,soft,rw"
      device: ":/srv/smbdata/media/config/prowlarr"
